name: Build Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release Version"
        required: true
        type: string
        default: "vx.x.x"

jobs:
  builds:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22.3"

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: false

      - name: Build
        env:
          NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build --ldflags="-s -w" -o bin/mangadex-chapter-pdf_linux_amd64 cmd/mangadex-chapter-pdf/*.go
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build --ldflags="-s -w" -o bin/mangadex-chapter-pdf_windows_amd64.exe cmd/mangadex-chapter-pdf/*.go
          CC="$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang" CXX="$NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang++" CGO_ENABLED=1 GOOS=android GOARCH=arm64 go build --ldflags="-s -w" -o bin/mangadex-chapter-pdf_android_arm64 cmd/mangadex-chapter-pdf/*.go

      - name: Save Artifact
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: |
            bin/mangadex-chapter-pdf_linux_amd64
            bin/mangadex-chapter-pdf_windows_amd64.exe
            bin/mangadex-chapter-pdf_android_arm64

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - builds
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: files
          path: files

      - name: Create Release and Upload Artifacts
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ inputs.version }}
          draft: true
          prerelease: true
          automatic_release_tag: ${{ inputs.version }}
          files: |
            files/*
